version: '3'

includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app

tasks:
  default:
    cmds:
      - task --list

  test:
    desc: "Ejecuta las pruebas unitarias para validar los pasos del ejercicio"
    dir: ./app
    cmds:
      - ./gradlew :shared:jvmTest

  desktop:
    desc: "Ejecuta la demo interactiva en Desktop (JVM)"
    dir: ./app
    cmds:
      - ./gradlew :desktopApp:run
